### ISSUE TITLE
Please provide the code

### ISSUE THREAD

**Issue by viveklpu2011** [jsuarezruiz/Art-Plant-Mall#1]
Please provide the code for Art Plant Mall

**Comment by TrueGeek** [comment]
Seconded, this looks very well done. I'd love to see if for the XAML alone.

**Comment by jsuarezruiz** [comment]
Of course, I will share the code!. At the moment it is not available because we are going to do this sample with live coding in Twitch https://www.twitch.tv/jsuarezruiz, starting this Tuesday (02 July).

**Comment by TrueGeek** [comment]
Awesome! Is there a time that's scheduled for?

**Comment by jsuarezruiz** [comment]
Yes, will start at 18:30h GMT+2.
